# Generated by Django 2.1.4 on 2018-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userTel', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=16)),
                ('userMail', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=20)),
            ],
        ),
    ]
