# Generated by Django 2.1.4 on 2018-12-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cs',
            fields=[
                ('csId', models.IntegerField(primary_key=True, serialize=False)),
                ('csAdd', models.CharField(max_length=50)),
                ('csStates', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='station.Cs')),
                ('userTel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Users')),
            ],
        ),
    ]
