# Generated by Django 2.1.4 on 2018-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='csFreeTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
